// File generated by Antigravity using android/app/google-services.json details.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.macOS:
        return macOS;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhdBMBfSqMnG3Gliv3JAxX4hB9t56inWs',
    appId: '1:224642107781:web:dd88ab7d9796e67ee59cec', // Placeholder Web App ID
    messagingSenderId: '224642107781',
    projectId: 'nearfind-2c220',
    authDomain: 'nearfind-2c220.firebaseapp.com',
    storageBucket: 'nearfind-2c220.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhdBMBfSqMnG3Gliv3JAxX4hB9t56inWs',
    appId: '1:224642107781:android:21d7a3a53185723ae59cec',
    messagingSenderId: '224642107781',
    projectId: 'nearfind-2c220',
    storageBucket: 'nearfind-2c220.firebasestorage.app',
  );

  static const FirebaseOptions macOS = FirebaseOptions(
    apiKey: 'AIzaSyAhdBMBfSqMnG3Gliv3JAxX4hB9t56inWs',
    appId: '1:224642107781:ios:21d7a3a53185723ae59cec', // Placeholder macOS/iOS App ID
    messagingSenderId: '224642107781',
    projectId: 'nearfind-2c220',
    storageBucket: 'nearfind-2c220.firebasestorage.app',
    iosBundleId: 'com.nearfind.app',
  );
}
